### ISSUE TITLE
Can't dye tubes

### ISSUE THREAD

**Issue by LordS3B** [Schmoller/Tubes#17] opened 2014-06-29 03:57 UTC
Hello. I'm having this problem:
When I right-click any kind of tube with a dye, the tube doesn't get colored, the player's hand doesn't even move. I can click ti with a water bucket, but not with dyes.
Things I tried:
Updating or downgrading MultiPart
Updating Forge
Isolating the mod
And they didn't work.
I'm using 1.7 and I don't want to downgrade to 1.6, and I wanna make a sorting systen. Please help me

**Comment by Schmoller** [comment] 2014-06-30 06:17
Ok I have found the cause of this, it will be fixed in the next version

**Closed as completed by Schmoller** 2014-06-30 06:17 UTC
